### ISSUE TITLE
S3 compatible endpoints?

### ISSUE THREAD

**Issue by codeagencybe** [OCA/storage#120]
Are these modules compatible with alternative S3 endpoints like WASABI, minio, digital ocean spaces etc...?
Or only Amazon AWS S3?
I couldn't find anything specific in the documentation about. 
All of the above mentioned endpoints can use the amazon BOTO/BOTO3 API 1:1 out of the box. 
The only requirement is having an option to point to a different endpoint/URL. 

Any feedback on this please?

**Comment by HviorForgeFlow** [comment]
https://github.com/OCA/storage/blob/d07126769c0dc54ad94394d84b5181cb5527beb3/storage_backend_s3/models/storage_backend.py#L28
https://github.com/OCA/storage/blob/d07126769c0dc54ad94394d84b5181cb5527beb3/storage_backend_s3/models/storage_backend.py#L29
