### ISSUE TITLE
[14.0][storage_backend_s3] strange workflow when deleting an image

### ISSUE THREAD

**Issue by Mat-moran** [OCA/storage#135]
Hi,

there some kind of bug in the image module `storage_backend_s3`

## How to replicate
- Load an image
- Delete the image
- Try to load the same image again and the error appear `ERROR: The private path must be uniq per backend`

**Comment by Mat-moran** [comment]
This is not an error or bug, sorry my fault.

but IMO is a **strange workflow**.

To remove completely the images from the backend S3 you need to execute the `Clean Storage File` action in the Files window and to do that you need to select at least one current file to be able to see the action menu.

- It this method not apply when you delete an image for some reason?
- If there is a reason... , It is not better to have a contextual button to run this method instead of have it inside the actions menu? Because this method is not related with any record in Files, it is just a method to remove in the remote backend the files that are not present in the odoo database

**Comment by Mat-moran** [comment]
Ok this is not an extrange workflow, is not the expected way to remove an image. 

I notice now that there is a cron job scheduled  every day that execute `_clean_storage_file` so there is no need to do it manually in a normal workflow. But if you are in a testing phase you should take it into account, so you mind if I do a PR reflecting this in the README?

**Comment by simahawk** [comment]
I missed this. Well, yes, the idea is that you can delete images fast by archiving them.
Having this written in the readme would be nice, feel free to open a PR for this or any other improvement :wink: 
Feel free to reopen if needed.
