### ISSUE TITLE
Documentation for getting storage_backend_s3 installed and running

### ISSUE THREAD

**Issue by gaganca** [OCA/storage#160]
I am facing issues setting up `storage_backend_s3` module on my odoo 14 installation and I feel this might not be the ideal place for such a question, but I couldn't find anything on the readme or any external blog post with guidance on how to set these up. 
Please let me know if you have a resource with installation instructions to get `storage_backend_s3` setup on a odoo install.

I have got the module added to my addons path and installed, deleted the default filesystem `StorageBackend` object, and created a `StorageBackend` object in the database with the S3 bucket details.

But nothing happens after all this setup, Odoo continues to reach the local filesystem for the files even if I create a new db or add attachments. 

Any help will be appreciated.

**Comment by luisovalles** [comment]
I have the same doubts and I have not been able to configure it. I have tried to install more modules from the storage repository but I still cannot move forward.

**Comment by mrsilph** [comment]
Hi! Anyone could set up it?

**Comment by simahawk** [comment]
`storage_backend* is not meant (yet) to modify ir.attachment storage or any other odoo core storage feature behavior.
This modules simply give you a way to manage ext storages.

Then we have `storage_[file|image|media]*` that allow you to store files, images and media on ext storage BUT NOT w/ standard odoo models. They are brand new models named `storage.[file|image|media]` and they should be used in specific applications where not supported (eg: shopinvader).

If you need to replace odoo core storage for attachments you can have a look at our modules here https://github.com/camptocamp/odoo-cloud-platform/

In the long term I'd like to plug storage_backend* w/ those cloud platform modules but for now they are totally independent.

**Comment by jackadam1981** [comment]
need a resource with installation instructions
