### ISSUE TITLE
Bug with storage_backend_ftp

### ISSUE THREAD

**Issue by apachebcn** [OCA/storage#163]
## Module
storage_backend_ftp

## Describe the bug
I create new storage with one ftp (tested with filezilla)
I add new storage entry in odoo with this ftp
I save and click test (test say ok)
I try to insert file with this ftp storage selected
It seem form is uploading file but is hung
console log say:
   /usr/lib/python3.7/ftplib.py(246)getresp()
   raise error_perm(resp)

**Comment by simahawk** [comment]
version? V13 got a fix recently here https://github.com/OCA/storage/pull/153

**Comment by apachebcn** [comment]
v14

**Comment by apachebcn** [comment]
storage_backend_ftp/components/ftp_adapter.py(96)
has:
-> raise ValueError(repr(e))
This do uncomprensible message to log
i add before:
-> print(str(e))
Then log print real problem with ftp: "553 Could not create file"

**Comment by apachebcn** [comment]
Log with ftp client debbuging print this:
sumex-es-odoo14     | *cmd* 'CWD ftp-test'
sumex-es-odoo14     | *resp* '250 Directory successfully changed.'
sumex-es-odoo14     | *cmd* 'TYPE I'
sumex-es-odoo14     | *resp* '200 Switching to Binary mode.'
sumex-es-odoo14     | *cmd* 'PASV'
sumex-es-odoo14     | *resp* '227 Entering Passive Mode (95,111,242,93,47,49).'
sumex-es-odoo14     | *cmd* 'STOR ftp-test/zzzzz-52'
sumex-es-odoo14     | *resp* '553 Could not create file.'
sumex-es-odoo14     | 553 Could not create file.
sumex-es-odoo14     | *cmd* 'QUIT'
sumex-es-odoo14     | *resp* '221 Goodbye.'

But i disabled "FTP Passive" from storage backend

**Comment by simahawk** [comment]
pls check if this fixes your problem https://github.com/OCA/storage/pull/165 (is getting merged)

**Comment by simahawk** [comment]
@apachebcn ping
