### ISSUE TITLE
RFC block RPC calls

### ISSUE THREAD

**Issue by simahawk** [OCA/storage#171]
A long time ago I've made storage.backend api public on https://github.com/OCA/storage/pull/75.
Some remarks where reported regarding exposing storage backend methods via RPC.
I've recently created a module to help protecting models from RPC calls: [rpc_helper](https://github.com/OCA/server-tools/tree/14.0/rpc_helper) and now I'm adding the possibility to [manage it via UI](https://github.com/OCA/server-tools/pull/2294).

To improve the security here we could:

1. recommend `rpc_helper` usage in the readme of `storage_backend`
2. make `storage_backend` depend on `rpc_helper` and block all calls by default
3. add a glue module (I don't think we need this given that you can configure via UI)

@lmignon @sebastienbeau @hparfr any opinion?

**Comment by lmignon** [comment]
>     1. recommend `rpc_helper` usage in the readme of `storage_backend`
> 
:+1:
