### ISSUE TITLE
[RFC] modern formats like `.webp` and `.avif`

### ISSUE THREAD

**Issue by Mat-moran** [OCA/storage#197]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
It would be interesting to extend the functionality of the image module to accept modern formats like `.webp`. I did not evaluate yet the difficulty of this but **what do you think about this matter?**

**Describe alternatives you've considered**
Extend the python decoder to accept modern formats like `.webp`.

**Additional context**

**Comment by sebastienbeau** [comment]
Hi I plan to work on it for version 16.
I will ping you want I will start to work on it
