### ISSUE TITLE
Instructions for how to use storage_backend_s3

### ISSUE THREAD

**Issue by bjellesma-cfs** [OCA/storage#199]
Hi, I'm having trouble finding documentation on how to use storage_backend to send files to an s3 bucket. Is there any documentation out there on how to use this that I'm not finding? If so, can this be added to the readme file?

**Comment by jackadam1981** [comment]
I didn't find any documents.

**Comment by jackadam1981** [comment]
My steps to use SFTP image module

I try to install and install dependencies one by one,

Configure and Test connection in technical(debug mode),

Then I checked the image source code and found the image widget, but it didn't work.

**Comment by bjellesma-cfs** [comment]
@jackadam1981 How did you configure and test in debug mode?

**Comment by jackadam1981** [comment]
https://github.com/OCA/storage/issues/200

**Comment by AungKoKoLin1997** [comment]
@bjellesma-cfs Did you find any documentation? I'm in trouble using this module.

**Comment by simahawk** [comment]
@bjellesma-cfs what's your problem specifically?


Here's an example of config from the env:
```
[storage_backend.name_of_your_backend]
backend_type=amazon_s3
served_by=external
base_url=https://your.cdn.domain.com
directory_path=foo  # if you want to store in this folder
url_include_directory_path=1  # if you want to include the above folder in the URL
aws_bucket=your-bucket-name
aws_file_acl=public-read
aws_access_key_id=$SECRET
aws_secret_access_key=$MORESECRET
aws_region=eu-central-1
```
I'm updating the readme of the module w/ this example.

**Comment by simahawk** [comment]
Here is it on v14 https://github.com/OCA/storage/tree/14.0/storage_backend_s3#example-of-configuration-via-env

**Comment by AungKoKoLin1997** [comment]
@simahawk Thanks for your configuration example. I can configure for amazon s3 and I install `storage_file` module. I can upload file to s3 using this module but I can't figure out how to get data back from s3. Am I misunderstanding the module? I try to catch up the documentation of `storage_xxx` modules but I don't have enough understanding of using these modules. the users like me will be happy if there is a USAGE.rst.

**Comment by simahawk** [comment]
Read/write operations are transparent to the end user: just use backends' public methods (`get`, `add`, `list_files`, etc)

**Comment by simahawk** [comment]
> how to get data back from S3

What do you mean? If you mean "from code" then you can simply do `backend.get(filepath)`.
It would be better if you explain precisely your use case otherwise it gets harder to understand what you are looking for....

**Comment by AungKoKoLin1997** [comment]
@simahawk 

> It would be better if you explain precisely your use case otherwise it gets harder to understand what you are looking for....

I would like to migrate database from v11.0 to 15.0 but we have a huge volume of filestore data (product images) around 100GB. So, I would to move all of the data to external storage before migration. After that, I want to do database migration.

After I read about your comment ((https://github.com/OCA/storage/issues/160#issuecomment-1137393549)), I think this module doesn't fit with my requirements.

**Comment by simahawk** [comment]
This module is not a replacement for attachment storage. At least not yet.

You might be interested in our cloud platform modules here https://github.com/camptocamp/odoo-cloud-platform/

**Comment by AungKoKoLin1997** [comment]
Yes. I think this can be fit with my requirement. I will check these modules. Thank you.
