### ISSUE TITLE
Access Forbidden

### ISSUE THREAD

**Issue by jayo2005** [OCA/storage#219]
I am getting Access forbidden when saving an image. I have check permnisionns and I can save files to the /root/images directory

![2022-11-04_12-39-26](https://user-images.githubusercontent.com/7015925/199974906-24164876-72f9-4687-b571-742611f157d7.png)
![2022-11-04_12-39-02](https://user-images.githubusercontent.com/7015925/199974918-df2655e7-4f43-4937-9422-206021c4cfe8.png)

**Comment by olivierb2** [comment]
I assume you cannot write in /root folder with odoo user.
