### ISSUE TITLE
[13.0] Unmet dependencies: storage_backend_sftp

### ISSUE THREAD

**Issue by amh-mw** [OCA/storage#47]
I've just pulled the latest 13.0 and it looks like storage_backend_sftp is not installable. When I add it as a dependency of my module, my installation fails with:

> 2020-05-12 18:45:48,719 32 INFO my_server odoo.modules.graph: module my_module: Unmet dependencies: storage_backend_sftp 

When I navigate to Apps to install it manually, there is no install button (or icon):
![Screen Shot 2020-05-12 at 2 51 22 PM](https://user-images.githubusercontent.com/495315/81733462-11863200-9460-11ea-86ef-d0c948ad2063.png)

Any suggestions on how I can start chasing this down?

**Comment by simahawk** [comment]
@amh-mw is not migrated yet https://github.com/OCA/storage/blob/13.0/storage_backend_sftp/__manifest__.py#L13

**Comment by simahawk** [comment]
BTW you can see it in the main readme of the repo under "unported addons" https://github.com/OCA/storage/tree/13.0

**Comment by simahawk** [comment]
https://github.com/OCA/storage/pull/50
